# Unique value constraint report for P683: report by value

SELECT
    ?value (SAMPLE(?valueLabel) AS ?valueLabel) (SAMPLE(?ct) AS ?ct)
    (GROUP_CONCAT(DISTINCT(STRAFTER(STR(?item), "/entity/")); separator=", ") AS ?items)
    (GROUP_CONCAT(DISTINCT(?itemLabel); separator=", ") AS ?itemLabels)
WHERE    
{
  	{ 	SELECT ?value (COUNT(DISTINCT ?item) as ?ct)
  		WHERE
  		{ 
  			?item wdt:P683 ?value 
		}
    	GROUP BY ?value HAVING (?ct>1) 
    	ORDER BY DESC(?ct)
	}
  	?item wdt:P683 ?value .
	SERVICE wikibase:label {
    	bd:serviceParam wikibase:language "en" . 
    	?item rdfs:label ?itemLabel .
    	?value rdfs:label ?valueLabel .
  	}
}
GROUP BY ?value
ORDER BY DESC(?ct)
