SELECT ?item ?pmc
WHERE 
{
  VALUES ?topic { wd:Q908902 wd:Q7202 } 
  ?item wdt:P31 wd:Q13442814.
  ?item p:P921 [ ps:P921 ?topic; pq:P642 wd:Q82069695 ].
  ?item wdt:P932 ?pmc.
  MINUS { ?item wdt:P2860 [] }
}
