SELECT DISTINCT ?ref ?refLabel ?date
{
  VALUES ?pw { wd:Q85438966 }
  VALUES ?top { wd:Q7202 wd:Q128406 wd:Q908902 }
  ?item p:P921 [ ps:P921 ?pw].
  ?item p:P921 [ ps:P921 ?top].
  ?item wdt:P2860 ?ref.
  MINUS { ?ref wdt:P921 wd:Q7202 }
  MINUS { ?ref wdt:P921 wd:Q128406 }
  MINUS { ?ref wdt:P921 wd:Q128570 }
  MINUS { ?ref wdt:P921 wd:Q908902 }
  MINUS { ?ref wdt:P921 wd:Q6926073 }
  MINUS { ?ref wdt:P921 wd:Q88161067 }
  ?ref rdfs:label ?refLabel.
  FILTER(LANG(?refLabel) = 'en' && (CONTAINS(STR(?refLabel), 'SARS')|| CONTAINS(STR(?refLabel), 'severe'))).
  ?ref wdt:P577 ?date.
}
