SELECT DISTINCT ?item ?stmt ?func ?fgo
WHERE 
{
  ?item wdt:P2926 ?ipr.
  MINUS { ?item wdt:P31 wd:Q898273 }
  OPTIONAL {
    ?item p:P680 ?stmt.
    ?stmt ps:P680 ?func.
    ?func wdt:P686 ?fgo
  }
}

