SELECT DISTINCT ?item ?ipr ?goid ?stmt ?prop
{
  ?item wdt:P2926 ?ipr.
  OPTIONAL {
    ?item p:P680 ?stmt.
    ?stmt ps:P680 ?func.
    ?stmt a wikibase:BestRank .
    ?func wdt:P686 ?goid
  }
  OPTIONAL {
    ?item ?prop wd:Q898273
  }
} 

