SELECT DISTINCT ?item ?p ?goid ?mtype ?rank ?supc
{ 
    VALUES ?groups { wd:Q67015883 wd:Q84467700 wd:Q417841 wd:Q7251477 wd:Q98119151 wd:Q81505329 wd:Q67101072 wd:Q67101749 wd:Q68461428 }
    ?item wdt:P31 ?groups.
    ?item p:P680 ?fstmt.
    ?fstmt ps:P680 ?p.
    ?p wdt:P686 ?goid.
    ?fstmt pq:P4390 ?mtype.
    ?fstmt wikibase:rank ?rank.
    OPTIONAL { ?item wdt:P279 ?supc }
}

