SELECT DISTINCT ?item ?goid ?stmt1 ?sgoid WHERE {
hint:Query hint:optimizer "None".
  ?item wdt:P686 ?goid.
  OPTIONAL {
      ?item p:P279 ?stmt1.
      ?stmt1 ps:P279 ?P279val.
      ?stmt1 a wikibase:BestRank .
      ?P279val wdt:P686 ?sgoid.
  }
}

