
        SELECT ?it ?prop ?val  (LANG(?val) AS ?lang)
        WHERE 
        {
          VALUES ?it { wd:Q47009619 wd:Q47009620 wd:Q47009721 wd:Q50351911 wd:Q53007244 wd:Q59926233 wd:Q59926235 }
          ?it ?prop ?val.
        }
        