
        SELECT ?it ?prop ?val  (LANG(?val) AS ?lang)
        WHERE 
        {
          VALUES ?it { wd:Q34330049 wd:Q34330053 wd:Q34330254 wd:Q38258785 wd:Q38258786 wd:Q50350797 wd:Q50351592 }
          ?it ?prop ?val.
        }
        