SELECT DISTINCT ?stmt1 ?stmt2
WHERE 
{
  ?item wdt:P31 wd:Q14860489.
  ?item p:P527 ?stmt1.
  VALUES ?partof { wd:Q96483149 wd:Q96483162 }
  ?stmt1 pq:P361 ?partof.
  MINUS { ?item wdt:P2888 ?exm.
         FILTER(STRSTARTS(STR(?exm), 'https://www.rhea-db.org/rhea/')) }
  OPTIONAL { ?stmt1 ps:P527 ?obj.
            ?obj p:P361 ?stmt2.
            ?stmt2 ps:P361 ?item }
}

